version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./html/modules/custom:/var/www/html/modules/custom
      - files:/var/www/html/sites/default/files
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - php
    ports:
      - "8888:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - files:/var/www/html/sites/default/files
volumes:
  files:
